pipeline {
    agent any

    tools {
        nodejs "Node-18"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/dinesh-kahar/angular-cicd-project.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build Angular App') {
            steps {
                sh 'npm run build --prod'
            }
        }

        stage('Run Unit Tests') {
            steps {
                sh 'npm test --watch=false --no-progress'
            }
        }

        stage('Archive Build Artifacts') {
            steps {
                archiveArtifacts artifacts: 'dist/**/*', fingerprint: true
            }
        }

        stage('Docker Build (Optional)') {
            when {
                expression { fileExists('Dockerfile') }
            }
            steps {
                sh 'docker build -t angular-cicd-app .'
            }
        }

    }

    post {
        success {
            echo "🎉 Build Completed Successfully!"
        }
        failure {
            echo "❌ Build Failed!"
        }
    }
}
